// ============== AUTH ============== //

export const REGISTER_SUCESS = 'REGISTER_SUCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCESS = 'LOGIN_SUCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const MENUS_HIDE = 'MENUS_HIDE';

// ============== SEARCH ============== //
export const SEARCH_VALUE = 'SEARCH_VALUE';
export const SEARCH_FETCH = 'SEARCH_FETCH';

// ============== FETCH ALABRA ============== //
export const FETCH_REST_PALABRA_DEFINICION = 'FETCH_REST_PALABRA_DEFINICION';
export const FETCH_REST_PALABRA_ERROR = 'FETCH_REST_PALABRA_ERROR';
export const FETCH_REST_PALABRA_SINONIMOS = 'FETCH_REST_PALABRA_SINONIMOS';
export const FETCH_REST_PALABRA_ANTONIMOS = 'FETCH_REST_PALABRA_ANTONIMOS';
export const FETCH_REST_PALABRA_IMAGES = 'FETCH_REST_PALABRA_IMAGES';
export const FETCH_REST_PALABRA_PICTOGRAMA = 'FETCH_REST_PALABRA_PICTOGRAMA';
export const FETCH_REST_PALABRA_PIXABAY = 'FETCH_REST_PALABRA_PIXABAY';
export const FETCH_REST_PALABRA_FLATICON = 'FETCH_REST_PALABRA_FLATICON';
export const FETCH_REST_PALABRA_LEXICA = 'FETCH_REST_PALABRA_LEXICA';
